# Generated by Django 3.2.6 on 2021-08-19 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.SmallIntegerField()),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(default='anonymous', max_length=30)),
                ('nickname', models.CharField(default='anonymous', max_length=30)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('karma', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
