# Generated by Django 3.2.6 on 2021-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ps',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='pw',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='transport',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
